### ISSUE TITLE
[feat] 1주차 과제

### ISSUE THREAD

**Issue by hyejungg** [SoptKopringStudy/HyeJung#2]
## 📌 Feature Issue
- 코틀린 문법을 이해하고 객체지향의 특성을 살려 프로그래밍해보기

## 📝 To-do

🌼 요구사항

- [x] 코틀린 자료구조를 이용하여 KStack 구현
- [x] KStack을 이용하여 백준 괄호문제 풀어보기
- [x] 영수증 출력 프로그램 작성해보기
