### ISSUE TITLE
[feat] 1주차 과제?

### ISSUE THREAD

**Issue by hyejungg** [SoptKopringStudy/HyeJung#3]
## 📌 Feature Issue
- springboot 프로젝트를 통해 API 구현해보기

## 📝 To-do

🌼 요구사항

- User api 구현하기
   - [ ] GET /user 
   - [ ] GET /user/name/{name}
   - [ ] GET /user/info/part=""?name=? 
   - [ ] POST /user
   - [ ] PUT /user 
   - [ ] DELETE /user/{id}
